const BASE_URL = import.meta.env.VITE_API_URL || '';

/**
 * Manages a short-lived download token for file URLs.
 * Uses a scoped JWT (5min expiry) instead of the full auth token to limit exposure.
 */
let _downloadToken: string | null = null;
let _downloadTokenExpires = 0;
let _tokenVersion = 0;
const _tokenListeners = new Set<() => void>();

/** Subscribe to download token changes (returns unsubscribe function) */
export function onDownloadTokenChange(listener: () => void): () => void {
  _tokenListeners.add(listener);
  return () => { _tokenListeners.delete(listener); };
}

/** Current token version — changes when a new download token is obtained */
export function getDownloadTokenVersion(): number {
  return _tokenVersion;
}

export async function refreshDownloadToken(): Promise<string | null> {
  const now = Date.now();
  if (_downloadToken && now < _downloadTokenExpires) return _downloadToken;

  const authToken = localStorage.getItem('token');
  if (!authToken) return null;

  try {
    const res = await fetch(`${BASE_URL}/files/download-token`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${authToken}`,
      },
    });
    if (!res.ok) return null;
    const data = await res.json();
    _downloadToken = data.token;
    _downloadTokenExpires = now + 4 * 60 * 1000; // refresh 1 min before expiry
    _tokenVersion++;
    _tokenListeners.forEach(fn => fn());
    return _downloadToken;
  } catch {
    return null;
  }
}

let _refreshInterval: ReturnType<typeof setInterval> | null = null;

export function startDownloadTokenRefresh() {
  stopDownloadTokenRefresh();
  refreshDownloadToken();
  _refreshInterval = setInterval(() => refreshDownloadToken(), 3 * 60 * 1000);
}

export function stopDownloadTokenRefresh() {
  if (_refreshInterval) {
    clearInterval(_refreshInterval);
    _refreshInterval = null;
  }
}

// Eagerly refresh on module load if authenticated
if (localStorage.getItem('token')) {
  startDownloadTokenRefresh();
}

/**
 * Appends a scoped download token to a file URL for use in <img> and <a> tags
 * that can't send Authorization headers.
 */
export function getAuthFileUrl(url: string, { download = false }: { download?: boolean } = {}): string {
  if (!url) return url;
  // Only append token to our own download endpoints, not external URLs (GCS signed URLs)
  if ((url.startsWith('/files/') || url.startsWith(`${BASE_URL}/files/`)) && url.includes('/download')) {
    let result = url;
    if (download) {
      const sep1 = result.includes('?') ? '&' : '?';
      result = `${result}${sep1}dl=1`;
    }
    const now = Date.now();
    if (_downloadToken && now < _downloadTokenExpires) {
      const sep2 = result.includes('?') ? '&' : '?';
      return `${result}${sep2}token=${_downloadToken}`;
    }
    // Token expired or missing — trigger async refresh for next render
    _downloadToken = null;
    refreshDownloadToken();
    return result;
  }
  return url;
}

/**
 * Returns a proxied file URL via the download endpoint.
 * This ensures a fresh signed URL is generated by the backend on each request,
 * avoiding GCS signed URL expiration issues (30-min TTL).
 */
export function getFileUrl(fileId: number): string {
  return getAuthFileUrl(`${BASE_URL}/files/${fileId}/download`);
}

/** Clear cached download token and stop refresh interval (call on logout) */
export function clearDownloadToken(): void {
  _downloadToken = null;
  _downloadTokenExpires = 0;
  stopDownloadTokenRefresh();
}

class ApiError extends Error {
  constructor(
    message: string,
    public status: number,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

async function request<T>(endpoint: string, options?: RequestInit): Promise<T> {
  const token = localStorage.getItem('token');

  const res = await fetch(`${BASE_URL}${endpoint}`, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...options?.headers,
    },
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({ error: 'Request failed' }));
    // Auto-logout on 401 (expired/invalid token).
    // Guard: only redirect once — concurrent 401s after token removal are no-ops.
    // Uses hard reload (window.location) so all in-memory Zustand state is wiped.
    if (res.status === 401 && localStorage.getItem('token')) {
      localStorage.removeItem('token');
      window.location.href = '/login';
    }
    const errorMsg = Array.isArray(body.error)
      ? body.error.map((e: { message?: string }) => e.message || 'Validation error').join(', ')
      : body.error || 'Request failed';
    throw new ApiError(errorMsg, res.status);
  }

  return res.json();
}

// ---- Auth ----

export interface AuthUser {
  id: number;
  email: string;
  name: string;
  avatar?: string | null;
  role?: 'ADMIN' | 'MEMBER' | 'GUEST';
  createdAt: string;
}

export interface AuthResponse {
  user: AuthUser;
  token: string;
}

export function googleLogin(credential: string) {
  return request<AuthResponse>('/auth/google', {
    method: 'POST',
    body: JSON.stringify({ credential }),
  });
}

// ---- Channels ----

export interface ApiChannel {
  id: number;
  name: string;
  isPrivate: boolean;
  createdAt: string;
  unreadCount: number;
  isMember: boolean;
  _count: { members: number; messages: number };
}

export function getChannels() {
  return request<ApiChannel[]>('/channels');
}

export function getChannel(id: number) {
  return request<ApiChannel>(`/channels/${id}`);
}

export function createChannel(name: string, isPrivate = false) {
  return request<ApiChannel>('/channels', {
    method: 'POST',
    body: JSON.stringify({ name, isPrivate }),
  });
}

export function joinChannel(id: number) {
  return request<{ message: string }>(`/channels/${id}/join`, { method: 'POST' });
}

export function leaveChannel(id: number) {
  return request<{ message: string }>(`/channels/${id}/leave`, { method: 'POST' });
}

export function markChannelRead(channelId: number, messageId: number) {
  return request<{ success: boolean }>(`/channels/${channelId}/read`, {
    method: 'POST',
    body: JSON.stringify({ messageId }),
  });
}

export function markChannelUnread(channelId: number, messageId: number) {
  return request<{ success: boolean }>(`/channels/${channelId}/unread`, {
    method: 'POST',
    body: JSON.stringify({ messageId }),
  });
}

export function markDMUnread(userId: number, messageId: number) {
  return request<{ markedAsUnread: number }>(`/dms/${userId}/unread`, {
    method: 'POST',
    body: JSON.stringify({ messageId }),
  });
}

export function pinDM(dmId: number) {
  return request(`/dms/messages/${dmId}/pin`, { method: 'POST' });
}

export function unpinDM(dmId: number) {
  return request(`/dms/messages/${dmId}/pin`, { method: 'DELETE' });
}

export function getPinnedDMs(userId: number) {
  return request<any[]>(`/dms/${userId}/pins`);
}

// ---- Messages ----

export interface ApiReaction {
  id: number;
  emoji: string;
  userId: number;
  messageId: number;
  createdAt: string;
  user: { id: number; name: string };
}

export interface ApiMessage {
  id: number;
  content: string;
  userId: number;
  channelId: number;
  threadId: number | null;
  isPinned?: boolean;
  pinnedBy?: number | null;
  pinnedAt?: string | null;
  editedAt?: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
  user: { id: number; name: string; email: string; avatar?: string | null };
  reactions: ApiReaction[];
  files: { id: number; filename: string; originalName: string; mimetype: string; size: number; url: string }[];
  _count: { replies: number };
  threadParticipants?: { id: number; name: string; avatar: string | null }[];
}

export interface MessagesResponse {
  messages: ApiMessage[];
  nextCursor?: number;
  hasMore: boolean;
}

export function getMessages(channelId: number, cursor?: number, limit = 50, around?: number) {
  const params = new URLSearchParams({ limit: String(limit) });
  if (cursor) params.set('cursor', String(cursor));
  if (around) params.set('around', String(around));
  return request<MessagesResponse>(`/channels/${channelId}/messages?${params}`);
}

export function sendMessage(channelId: number, content: string, fileIds?: number[]): Promise<ApiMessage> {
  return request<ApiMessage>(`/channels/${channelId}/messages`, {
    method: 'POST',
    body: JSON.stringify({ content, ...(fileIds?.length ? { fileIds } : {}) }),
  });
}

// ---- Reactions ----

export function addReaction(messageId: number, emoji: string) {
  return request<ApiReaction>(`/messages/${messageId}/reactions`, {
    method: 'POST',
    body: JSON.stringify({ emoji }),
  });
}

export function removeReaction(messageId: number, emoji: string) {
  return request<{ message: string }>(
    `/messages/${messageId}/reactions/${encodeURIComponent(emoji)}`,
    { method: 'DELETE' },
  );
}

// ---- Pins ----

export function pinMessage(messageId: number) {
  return request<ApiMessage>(`/messages/${messageId}/pin`, { method: 'POST' });
}

export function unpinMessage(messageId: number) {
  return request<ApiMessage>(`/messages/${messageId}/pin`, { method: 'DELETE' });
}

export function getPinnedMessages(channelId: number) {
  return request<ApiMessage[]>(`/channels/${channelId}/pins`);
}

// ---- Threads ----

export function getThread(messageId: number) {
  return request<{ parent: ApiMessage; replies: ApiMessage[] }>(
    `/messages/${messageId}/thread`,
  );
}

export function replyToMessage(messageId: number, content: string, fileIds?: number[]) {
  return request<ApiMessage>(`/messages/${messageId}/reply`, {
    method: 'POST',
    body: JSON.stringify({ content, ...(fileIds?.length ? { fileIds } : {}) }),
  });
}

// ---- Messages (edit/delete) ----

export function editMessage(messageId: number, content: string) {
  return request<ApiMessage>(`/messages/${messageId}`, {
    method: 'PATCH',
    body: JSON.stringify({ content }),
  });
}

export function deleteMessage(messageId: number) {
  return request<{ message: string }>(`/messages/${messageId}`, {
    method: 'DELETE',
  });
}

// ---- Search ----

export interface SearchResult {
  id: number;
  type: 'message' | 'dm';
  content: string;
  createdAt: string;
  user: { id: number; name: string; email: string; avatar?: string | null };
  channel?: { id: number; name: string };
  participant?: { id: number; name: string; email: string };
}

export interface SearchResponse {
  results: SearchResult[];
  query: string;
  counts: { messages: number; dms: number; total: number };
}

export function searchMessages(query: string, channelId?: number) {
  const params = new URLSearchParams({ q: query });
  if (channelId) params.set('channelId', String(channelId));
  return request<SearchResponse>(`/search?${params}`);
}

// ---- Files ----

export interface ApiFile {
  id: number;
  filename: string;
  originalName: string;
  mimetype: string;
  size: number;
  url: string;
}

export interface ApiFileWithUser extends ApiFile {
  createdAt: string;
  user: { id: number; name: string; email: string; avatar?: string | null };
}

export function getChannelFiles(channelId: number) {
  return request<ApiFileWithUser[]>(`/channels/${channelId}/files`);
}

export function getUserFiles() {
  return request<ApiFileWithUser[]>('/files');
}

export async function uploadFile(file: File): Promise<ApiFile> {
  const token = localStorage.getItem('token');
  const formData = new FormData();
  formData.append('file', file);

  const res = await fetch(`${BASE_URL}/files`, {
    method: 'POST',
    headers: {
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    body: formData,
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({ error: 'Upload failed' }));
    throw new ApiError(body.error || 'Upload failed', res.status);
  }

  return res.json();
}

// ---- Users ----

export function getUsers(search?: string) {
  const params = new URLSearchParams({ limit: '50' });
  if (search) params.set('search', search);
  return request<AuthUser[]>(`/users?${params}`);
}

// ---- User Profile ----

export interface UserProfile {
  id: number;
  email: string;
  name: string;
  avatar?: string | null;
  role?: 'ADMIN' | 'MEMBER' | 'GUEST';
  status?: string;
  bio?: string | null;
  createdAt: string;
  _count?: { messages: number; channels: number };
}

export function getMyProfile() {
  return request<UserProfile>('/users/me');
}

export function updateMyProfile(data: { name?: string; avatar?: string | null; status?: string; bio?: string | null }) {
  return request<UserProfile>('/users/me', {
    method: 'PATCH',
    body: JSON.stringify(data),
  });
}

export async function uploadAvatar(file: Blob): Promise<UserProfile> {
  const token = localStorage.getItem('token');
  const formData = new FormData();
  formData.append('avatar', file);

  const res = await fetch(`${BASE_URL}/users/me/avatar`, {
    method: 'POST',
    headers: {
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    body: formData,
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({ error: 'Upload failed' }));
    throw new ApiError(body.error || 'Upload failed', res.status);
  }

  return res.json();
}

export function getUserProfile(userId: number) {
  return request<UserProfile>(`/users/${userId}`);
}

// ---- Direct Messages ----

export interface ApiDMConversation {
  otherUser: { id: number; name: string; email: string; avatar?: string | null; status?: string };
  lastMessage: { content: string; createdAt: string; fromUserId: number } | null;
  unreadCount: number;
}

export interface ApiDMReaction {
  id: number;
  emoji: string;
  userId: number;
  dmId: number;
  user: { id: number; name: string };
}

export interface ApiDirectMessage {
  id: number;
  content: string;
  fromUserId: number;
  toUserId: number;
  threadId?: number | null;
  isPinned?: boolean;
  createdAt: string;
  updatedAt: string;
  editedAt: string | null;
  deletedAt: string | null;
  fromUser: { id: number; name: string; email: string; avatar?: string | null };
  toUser: { id: number; name: string; email: string; avatar?: string | null };
  reactions?: ApiDMReaction[];
  _count?: { replies: number };
  threadParticipants?: { id: number; name: string; avatar: string | null }[];
}

export function getDirectMessages() {
  return request<ApiDMConversation[]>('/dms');
}

export function getConversation(userId: number, cursor?: number, around?: number) {
  const params = new URLSearchParams();
  if (cursor) params.set('cursor', String(cursor));
  if (around) params.set('around', String(around));
  return request<{ messages: ApiDirectMessage[]; hasMore: boolean }>(`/dms/${userId}?${params}`);
}

export function sendDM(toUserId: number, content: string, fileIds?: number[]) {
  return request<ApiDirectMessage>('/dms', {
    method: 'POST',
    body: JSON.stringify({ toUserId, content, fileIds }),
  });
}

export function editDM(dmId: number, content: string) {
  return request<ApiDirectMessage>(`/dms/messages/${dmId}`, {
    method: 'PATCH',
    body: JSON.stringify({ content }),
  });
}

export function deleteDM(dmId: number) {
  return request<{ message: string }>(`/dms/messages/${dmId}`, {
    method: 'DELETE',
  });
}

export function getDMThread(dmId: number) {
  return request<{ parent: ApiDirectMessage; replies: ApiDirectMessage[] }>(
    `/dms/messages/${dmId}/thread`,
  );
}

export function replyToDM(dmId: number, content: string, fileIds?: number[]) {
  return request<ApiDirectMessage>(`/dms/messages/${dmId}/reply`, {
    method: 'POST',
    body: JSON.stringify({ content, fileIds }),
  });
}

export function addDMReaction(dmId: number, emoji: string) {
  return request<ApiDMReaction>(`/dms/messages/${dmId}/reactions`, {
    method: 'POST',
    body: JSON.stringify({ emoji }),
  });
}

export function removeDMReaction(dmId: number, emoji: string) {
  return request<{ message: string }>(`/dms/messages/${dmId}/reactions/${encodeURIComponent(emoji)}`, {
    method: 'DELETE',
  });
}

// ---- Bookmarks ----

export interface ApiBookmark {
  messageId: number;
  createdAt: string;
}

export function getBookmarks() {
  return request<ApiBookmark[]>('/bookmarks');
}

export function addBookmark(messageId: number) {
  return request<ApiBookmark>(`/messages/${messageId}/bookmark`, { method: 'POST' });
}

export function removeBookmark(messageId: number) {
  return request<{ message: string }>(`/messages/${messageId}/bookmark`, { method: 'DELETE' });
}

// ---- Channel Members ----

export interface ChannelMember {
  userId: number;
  channelId: number;
  channelRole?: 'OWNER' | 'MODERATOR' | 'MEMBER';
  joinedAt: string;
  user: {
    id: number;
    name: string;
    email: string;
    avatar?: string | null;
    status: string;
    isOnline: boolean;
    lastSeen?: string;
  };
}

export function getChannelMembers(channelId: number) {
  return request<ChannelMember[]>(`/channels/${channelId}/members`);
}

export function addChannelMember(channelId: number, userId: number) {
  return request<{ message: string }>(`/channels/${channelId}/members`, {
    method: 'POST',
    body: JSON.stringify({ userId }),
  });
}

// ---- Scheduled Messages ----

export interface ApiScheduledMessage {
  id: number;
  content: string;
  channelId: number;
  userId: number;
  scheduledAt: string;
  createdAt: string;
  sent: boolean;
  channel: { id: number; name: string };
}

export function scheduleMessage(channelId: number, content: string, scheduledAt: Date) {
  return request<ApiScheduledMessage>('/messages/schedule', {
    method: 'POST',
    body: JSON.stringify({ channelId, content, scheduledAt: scheduledAt.toISOString() }),
  });
}

export function getScheduledMessages() {
  return request<ApiScheduledMessage[]>('/messages/scheduled');
}

export function cancelScheduledMessage(id: number) {
  return request<{ success: boolean }>(`/messages/scheduled/${id}`, { method: 'DELETE' });
}

export function editScheduledMessage(id: number, data: { content?: string; scheduledAt?: string }) {
  return request<ApiScheduledMessage>(`/messages/scheduled/${id}`, {
    method: 'PATCH',
    body: JSON.stringify(data),
  });
}

export function sendScheduledMessageNow(id: number) {
  return request<{ success: boolean; message: unknown }>(`/messages/scheduled/${id}/send`, {
    method: 'POST',
  });
}

// ---- Admin ----

export interface AdminUser {
  id: number;
  email: string;
  name: string;
  avatar?: string | null;
  role: 'OWNER' | 'ADMIN' | 'MEMBER' | 'GUEST';
  status?: string;
  deactivatedAt?: string | null;
  createdAt: string;
}

export interface AdminChannel {
  id: number;
  name: string;
  isPrivate: boolean;
  createdBy?: number | null;
  archivedAt?: string | null;
  createdAt: string;
  _count: { members: number; messages: number };
}

export interface AuditLogEntry {
  id: number;
  action: string;
  actorId: number;
  targetType: string;
  targetId?: number | null;
  targetName?: string | null;
  details?: string | null;
  createdAt: string;
  actor: { id: number; name: string; avatar?: string | null };
}

export interface AdminInvite {
  id: number;
  code: string;
  createdBy: number;
  role: 'OWNER' | 'ADMIN' | 'MEMBER' | 'GUEST';
  maxUses: number | null;
  useCount: number;
  expiresAt: string | null;
  createdAt: string;
  creator: { id: number; name: string };
}

export function adminGetUsers() {
  return request<AdminUser[]>('/admin/users');
}

export function adminTransferOwnership(userId: number) {
  return request<{ message: string }>('/admin/transfer-ownership', {
    method: 'POST',
    body: JSON.stringify({ userId }),
  });
}

export function adminUpdateUserRole(userId: number, role: 'ADMIN' | 'MEMBER' | 'GUEST') {
  return request<AdminUser>(`/admin/users/${userId}`, {
    method: 'PATCH',
    body: JSON.stringify({ role }),
  });
}

export function adminDeactivateUser(userId: number) {
  return request<AdminUser>(`/admin/users/${userId}/deactivate`, { method: 'POST' });
}

export function adminReactivateUser(userId: number) {
  return request<AdminUser>(`/admin/users/${userId}/reactivate`, { method: 'POST' });
}

export function adminGetChannels() {
  return request<AdminChannel[]>('/admin/channels');
}

export function adminDeleteChannel(channelId: number) {
  return request<{ message: string }>(`/admin/channels/${channelId}`, { method: 'DELETE' });
}

export function adminArchiveChannel(channelId: number) {
  return request<AdminChannel>(`/admin/channels/${channelId}/archive`, { method: 'POST' });
}

export function adminUnarchiveChannel(channelId: number) {
  return request<AdminChannel>(`/admin/channels/${channelId}/unarchive`, { method: 'POST' });
}

export function adminEditChannel(channelId: number, data: { name?: string; isPrivate?: boolean }) {
  return request<AdminChannel>(`/admin/channels/${channelId}`, {
    method: 'PATCH',
    body: JSON.stringify(data),
  });
}

export function adminGetAuditLog(limit = 50, offset = 0) {
  return request<{ entries: AuditLogEntry[]; total: number }>(`/admin/audit-log?limit=${limit}&offset=${offset}`);
}

export function adminGetInvites() {
  return request<AdminInvite[]>('/admin/invites');
}

export function adminCreateInvite(data: { role?: string; maxUses?: number | null; expiresAt?: string | null }) {
  return request<AdminInvite>('/admin/invites', {
    method: 'POST',
    body: JSON.stringify(data),
  });
}

export function adminDeleteInvite(inviteId: number) {
  return request<{ message: string }>(`/admin/invites/${inviteId}`, { method: 'DELETE' });
}
